### ISSUE TITLE
Need to refresh the page after first network slice creation

### ISSUE THREAD

**Issue by gruyaume** [canonical/sdcore-nms#202]
#### Describe the bug
After creating the first network slice, we have to refresh the page to see that it was actually created and not the "empty page" content.

#### To Reproduce

1. Deploy SD-Core
2. Create a network slice
3. Refresh the page

#### Expected behavior

The network slice shows up automatically

**Comment by patriciareinoso** [comment]
This bug no longer exists on the NMS. After creating the first Network Slice it shows up immediately
