### ISSUE TITLE
User should be informed if the config files are missing

### ISSUE THREAD

**Issue by patriciareinoso** [canonical/sdcore-nms#206]
#### Description

When we run the NMS and the config files are not found (either `UPF_CONFIG_PATH` / `GNB_CONFIG_PATH` haven't been set or the files do not exist) there is only a log as follows: 

![image](https://github.com/canonical/sdcore-nms/assets/10354025/d107e1bf-4e19-4b75-a18c-802785b8f09d)

#### To Reproduce

set `WEBUI_ENDPOINT`
don't set `UPF_CONFIG_PATH` or `GNB_CONFIG_PATH`
Run the service.

#### Expected behavior

The GUI should show a message indicating that the config files are missing. 
Something similar to when the webui cannot be found

![image](https://github.com/canonical/sdcore-nms/assets/10354025/8f808760-aeca-4c78-a4d7-d10e1c52f189)

**Comment by gruyaume** [comment]
I believe this is not applicable anymore since we don't have such config files.
