### ISSUE TITLE
Network slice delete leaves Device group objects in the DB

### ISSUE THREAD

**Issue by patriciareinoso** [canonical/sdcore-nms#227]
#### Describe the bug

When a Network Slice is deleted, it's associated Device Group objects are not removed from the DB.
There is no way to remove these records from the GUI.

#### To Reproduce

1. Add a Network Slice 
2. Default Device Group is automatically added
3. Add another Device Group
4. Delete the Network Slice 
5. Check the webconsoleData.snapshots.devGroupData collection in MongoDB -> Both Device Groups exist

#### Expected behavior

When the Network Slice is deleted the associated Device Groups are deleted as well.

#### Screenshots

![image](https://github.com/canonical/sdcore-nms/assets/10354025/d87dadf8-bec0-4634-b028-9781cca8dd56)

**Comment by gruyaume** [comment]
@patriciareinoso Is this problem also occurring with the curl calls made directly to webui? If yes it's likely an issue with webui and not the NMS and we should file the bug there instead.

**Comment by patriciareinoso** [comment]
> @patriciareinoso Is this problem also occurring with the curl calls made directly to webui? If yes it's likely an issue with webui and not the NMS and we should file the bug there instead.

Indeed, we get the same behavior with curl

![image](https://github.com/canonical/sdcore-nms/assets/10354025/09e8d69d-fc26-4660-9101-d339eed4bada)

**Comment by gruyaume** [comment]
@patriciareinoso Can you please open a bug in the upstream webui project? Once this is done we can close this one here and address it there.

**Comment by patriciareinoso** [comment]
https://github.com/canonical/sdcore-nms/pull/246 handles this problem. 
It's no longer possible to delete a network slice that contains device groups. 
It's no longer possible to delete a device group that contains subscribers. 
I'll open the bug in the updstream project
