### ISSUE TITLE
Creating a second slice replaces default device group

### ISSUE THREAD

**Issue by markbeierl** [canonical/sdcore-nms#230]
#### Describe the bug
Default device group is overwritten every time a slice is created

#### To Reproduce

1. Create a slice
2. Delete the default device group
3. Create a new default device group with different values
4. Confirm new values are present
5. Create a new slice
6. Reload the page and note the reset in slice 1's default

#### Screenshots
First slice
![image](https://github.com/canonical/sdcore-nms/assets/19839294/057ee041-706c-4d41-bb68-0da10278dafe)
Second slice, both defaults are set back to initial values
![image](https://github.com/canonical/sdcore-nms/assets/19839294/353c1bf4-397f-466d-8a6d-ac2c5fe811ae)

**Comment by patriciareinoso** [comment]
After https://github.com/canonical/sdcore-nms/pull/226 the default Device Group is no longer called default. So it should help with this issue.
I agree we should check whether the DG exist before creating it. It's in  the backlog
