### ISSUE TITLE
gNB and UPF error message does not dissapear after lists are updated in create NS modal

### ISSUE THREAD

**Issue by patriciareinoso** [canonical/sdcore-nms#520]
#### Describe the bug

In the NMS if we remove the relation between the NMS and the gnbsim/UPF, an error message is shown in the Create NS modal.

`Failed to retrieve the list of GNBs from the server.` 

After we restore the relations and the gnb/upf config files updated and they are shown in the Create Network Slice modal, the error message is still shown. It takes some time to be dissapear.

#### To Reproduce

1. Deploy SD-Core with a gnbsim
2. Go to the NMS GUI
3. Try to create a NS -> 1 gnb is on the list
4. Remove the relation between the gnbsim  and the NMS
5. Wait for the gnbsim list to be updated (beware of https://github.com/canonical/sdcore-nms-k8s-operator/issues/27)
6. Try to create a NS -> The `Failed to retrieve the list of GNBs from the server.` message appears and there are no gnbs on the list.
8. Restore the relation between the gnbsim and the NMS 
9. Open the Create NS modal
10. Wait for the gnb list to be updated -> 1 gnb is on the list but the `Failed to retrieve the list of GNBs from the server.` is still there

Same procedure for the UPF.

#### Expected behavior

As soon as the gnb/upf list is updated, the error message dissapears.

#### Screenshots

![image](https://github.com/canonical/sdcore-nms/assets/10354025/05d93114-ffaf-4e46-9ccd-7fe368c63c38)

![image](https://github.com/canonical/sdcore-nms/assets/10354025/06d0728f-01e4-4296-8ac3-4cd01198741a)

#### Environment

- Charm / library version (if relevant): : 1.3 edge
- Juju version (output from `juju --version`): 3.4
- Cloud Environment:  microk8s
- Kubernetes version (output from `kubectl version --short`): 1.27

**Comment by patriciareinoso** [comment]
May be related to https://github.com/canonical/sdcore-nms/issues/526

**Comment by gruyaume** [comment]
Is this issue still relevant?

**Comment by gruyaume** [comment]
Closing as I have not been experimenting this issue. This likely was fixed when we merged nms with the upstream webconsole.
