### ISSUE TITLE
Incorrect format on the config files does not show error message

### ISSUE THREAD

**Issue by patriciareinoso** [canonical/sdcore-nms#526]
#### Describe the bug

When the `upf_config.json` or the `gnb_config.json` files do not have the correct format, the error message is not shown.

#### To Reproduce

1. Put invalid content in the `upf_config.json` file
2. Run the NMS server 
4. Try to create a Network Slice

Same for the `gnb_config.json` file

#### Expected behavior

The error messages is shown as soon as we open the create Network Slice modal. The same way as it is done when the files contain empty lists.

![image](https://github.com/canonical/sdcore-nms/assets/10354025/6894cb83-3715-4b45-90df-7a54997e5f77)

#### Screenshots

![image](https://github.com/canonical/sdcore-nms/assets/10354025/984a8ff7-0f75-4c7c-b85e-33a8f458d31c)

![image](https://github.com/canonical/sdcore-nms/assets/10354025/83cbbd68-abaf-4f41-a95c-a104e789f835)

#### Logs

We can only see the failure in the logs:
```
Failed to read UPF config file: SyntaxError: Unexpected token 's', "[
somethng
]
" is not valid JSON
    at JSON.parse (<anonymous>)
    at handleGET (webpack-internal:///(api)/./pages/api/upf.ts:28:34)
    at upf (webpack-internal:///(api)/./pages/api/upf.ts:14:19)
    at /home/reinoso/dev/repos/sdcore-nms/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3039
    at /home/reinoso/dev/repos/sdcore-nms/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/home/reinoso/dev/repos/sdcore-nms/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/home/reinoso/dev/repos/sdcore-nms/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
```

**Comment by gruyaume** [comment]
This does not apply now that we don't have config files anymore
